version: '3.9'

services:
  go-app:
    container_name: go-app
    build: .
    environment:
      DATABASE_URL: "host=go-db user=postgres password=postgres dbname=go-auth sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - go-db
    volumes:
      - ./:/app
  go-db:
    container_name: go-db
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: go-auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}